---
plugin: 'ansible.builtin.constructed'
strict: true
use_vars_plugins: true
use_extra_vars: true

groups:
  cnd_rhel_8: "ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'"

keyed_groups:
  - prefix: 'cnd'
    key: >-
      (
        inventory_hostname !=
        inventory_hostname_short
      ) | ansible.builtin.ternary(
        inventory_hostname |
        ansible.builtin.split('.') |
        reject('match', inventory_hostname_short) |
        join('_'),
        'no_fqdn'
      )

...
